services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: majoo_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        environment:
            APP_ENV: local
            APP_KEY: ${APP_KEY}
            APP_DEBUG: true
            DB_CONNECTION: pgsql
            DB_HOST: pgsql
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE:-laravel}
            DB_USERNAME: ${DB_USERNAME:-sail}
            DB_PASSWORD: ${DB_PASSWORD:-secret}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - majoo_network

    nginx:
        image: nginx:alpine
        container_name: majoo_nginx
        restart: unless-stopped
        ports:
            - '${APP_PORT:-8000}:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - majoo_network

    pgsql:
        image: 'postgres:15'
        container_name: majoo_pgsql
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-5435}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-laravel}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'majoo-pgsql:/var/lib/postgresql/data'
        networks:
            - majoo_network
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE:-laravel}'
                - '-U'
                - '${DB_USERNAME:-sail}'
            retries: 5
            timeout: 5s
            interval: 5s

    redis:
        image: 'redis:alpine'
        container_name: majoo_redis
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'majoo-redis:/data'
        networks:
            - majoo_network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 5
            timeout: 5s
            interval: 5s

networks:
    majoo_network:
        driver: bridge

volumes:
    majoo-pgsql:
        driver: local
    majoo-redis:
        driver: local
